name: Release
on:
  push:
    branches:
      - main
jobs:
  change_verify:
    name: Verify that changes has been properly documentated.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Rush project
        run: node common/scripts/install-run-rush.js install
      - name: Check for undescribed changes.
        run: node common/scripts/install-run-rush.js change -v
      - name: Build affected projects
        run: node common/scripts/install-run-rush.js build --to tag:cli
      - name: Publish affected packages to NPMJS.
        run: node common/scripts/install-run-rush.js publish --apply --target-branch main --publish
