name: Rush
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  change_verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # - uses: pnpm/action-setup@v2.0.1
      #   name: Install pnpm
      #   id: pnpm-install
      #   with:
      #     version: 7
      #     run_install: false

      # - name: Get pnpm store directory
      #   id: pnpm-cache
      #   run: |
      #     echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      # - uses: actions/cache@v3
      #   name: Setup pnpm cache
      #   with:
      #     path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
      #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-store-

      - name: Setup Rush project
        run: node common/scripts/install-run-rush.js install

      - name: Check for undocumented changes.
        run: node common/scripts/install-run-rush.js change -v

      - name: Build affected projects
        run: node common/scripts/install-run-rush.js build --to tag:cli

      - name: Publish affected packages to NPMJS.
        run: node common/scripts/install-run-rush.js publish --apply --target-branch main --publish
